//
//  Icon.swift
//  ExpenseTracker
//
//  Created by Hubert Klonowski on 05.09.2024.
//

import Foundation

enum Icon: String, RawRepresentable, CaseIterable, Identifiable {
    var id : String { self.rawValue }
    
    case tag = "tag.fill"
    case phone = "phone.fill"
    case video = "video.fill"
    case envelope = "envelope.fill"
    case sun = "sun.max.fill"
    case moon = "moon.fill"
    case sparkles = "sparkles"
    case cloud = "cloud.fill"
    case rainbow = "rainbow"
    case location = "location.fill"
    case car = "car.fill"
    case tram = "tram.fill"
    case bicycle = "bicycle"
    case fuelpump = "fuelpump.fill"
    case binocular = "binoculars.fill"
    case brush = "paintbrush.pointed.fill"
    case eyebrow = "eyebrow"
    case externalDrive = "externaldrive.fill"
    case doc = "doc.fill"
    case booksVertical = "books.vertical.fill"
    case bookClosed = "book.closed.fill"
    case textBook = "text.book.closed.fill"
    case magazine = "magazine.fill"
    case newspaper = "newspaper.fill"
    case bookmark = "bookmark.fill"
    case graduationCap = "graduationcap.fill"
    case backpack = "backpack.fill"
    case studentDesk = "studentdesk"
    case paperclip = "paperclip"
    case dumbbell = "dumbbell.fill"
    case soccerBall = "soccerball"
    case basketball = "basketball.fill"
    case trophy = "trophy.fill"
    case mic = "music.mic"
    case flag = "flag.fill"
    case flagCheckered = "flag.checkered"
    case bell = "bell.fill"
    case camera = "camera.fill"
    case bag = "bag.fill"
    case cart = "cart.fill"
    case basket = "basket.fill"
    case creditcard = "creditcard.fill"
    case wand = "wand.and.stars"
    case dice = "die.face.3.fill"
    case piano = "pianokeys.inverse"
    case paintBrush = "paintbrush.fill"
    case hammer = "hammer.fill"
    case suitcase = "suitcase.fill"
    case theaterMasks = "theatermasks.fill"
    case powerplug = "powerplug.fill"
    case spigot = "spigot.fill"
    case partyPopper = "party.popper.fill"
    case ballon = "balloon.fill"
    case popcorn = "popcorn.fill"
    case bed = "bed.double.fill"
    case toilet = "toilet.fill"
    case lock = "lock.fill"
    case key = "key.fill"
    case map = "map.fill"
    case headphones = "headphones"
    case evCharger = "ev.charger.fill"
    case syringe = "syringe.fill"
    case pill = "pill.fill"
    case flask = "flask.fill"
    case teddybear = "teddybear.fill"
    case tree = "tree.fill"
    case hanger = "hanger"
    case tshirt = "tshirt.fill"
    case shoe = "shoe.fill"
    case film = "film.fill"
    case movieClapper = "movieclapper.fill"
    case eyeglasses = "eyeglasses"
    case clock = "clock.fill"
    case alarm = "alarm.fill"
    case gameController = "gamecontroller.fill"
    case paintPalette = "paintpalette.fill"
    case cupAndSaucer = "cup.and.saucer.fill"
    case mug = "mug.fill"
    case takeout = "takeoutbag.and.cup.and.straw.fill"
    case carrot = "carrot.fill"
    case forkAndKnife = "fork.knife"
    case globeDesk = "globe.desk.fill"
    case gift = "gift.fill"
    case battery100percent = "battery.100percent"
    case iphone = "iphone"
    case macbook = "macbook"
    case appleLogo = "apple.logo"
    case applewatch = "applewatch"
    case appleTV = "appletv.fill"
    case remote = "appletvremote.gen4.fill"
    case airplaneDeparture = "airplane.departure"
    case airplaneArrival = "airplane.arrival"
    case airplane = "airplane"
    case person = "person.fill"
    case people = "person.3.fill"
    case eyes = "eyes.inverse"
    case mouth = "mouth.fill"
    case brain = "brain.fill"
    case globe = "globe.europe.africa.fill"
    case pawprint = "pawprint.fill"
    case flower = "camera.macro"
    case atom = "atom"
    case heart = "heart.fill"
    case stethoscope = "stethoscope"
    case cross = "cross.circle.fill"
    case squareRoot = "x.squareroot"
    case function = "function"
    
    
//  //////////////////////////////////////////////
    
    var localized: LocalizedStringResource {
        
        switch self {
            
        case .tag: "ICON_TAG"
        case .phone: "ICON_PHONE"
        case .video: "ICON_VIDEO"
        case .envelope: "ICON_ENVELOPE"
        case .sun: "ICON_SUN"
        case .moon: "ICON_MOON"
        case .sparkles: "ICON_SPARKLES"
        case .cloud: "ICON_CLOUD"
        case .rainbow: "ICON_RAINBOW"
        case .location: "ICON_LOCATION"
        case .car: "ICON_CAR"
        case .tram: "ICON_TRAM"
        case .bicycle: "ICON_BICYCLE"
        case .fuelpump: "ICON_FUELPUMP"
        case .binocular: "ICON_BINOCULAR"
        case .brush: "ICON_BRUSH"
        case .eyebrow: "ICON_EYEBROW"
        case .externalDrive: "ICON_EXTERNAL_DRIVE"
        case .doc: "ICON_DOC"
        case .booksVertical: "ICON_BOOKS_VERTICAL"
        case .bookClosed: "ICON_BOOK_CLOSED"
        case .textBook: "ICON_TEXT_BOOK"
        case .magazine: "ICON_MAGAZINE"
        case .newspaper: "ICON_NEWSPAPER"
        case .bookmark: "ICON_BOOKMARK"
        case .graduationCap: "ICON_GRADUATION_CAP"
        case .backpack: "ICON_BACKPACK"
        case .studentDesk: "ICON_STUDENT_DESK"
        case .paperclip: "ICON_PAPERCLIP"
        case .dumbbell: "ICON_DUMBBELL"
        case .soccerBall: "ICON_SOCCER_BALL"
        case .basketball: "ICON_BASKETBALL"
        case .trophy: "ICON_TROPHY"
        case .mic: "ICON_MIC"
        case .flag: "ICON_FLAG"
        case .flagCheckered: "ICON_FLAG_CHECKERED"
        case .bell: "ICON_BELL"
        case .camera: "ICON_CAMERA"
        case .bag: "ICON_BAG"
        case .cart: "ICON_CART"
        case .basket: "ICON_BASKET"
        case .creditcard: "ICON_CREDITCARD"
        case .wand: "ICON_WAND"
        case .dice: "ICON_DICE"
        case .piano: "ICON_PIANO"
        case .paintBrush: "ICON_PAINT_BRUSH"
        case .hammer: "ICON_HAMMER"
        case .suitcase: "ICON_SUITCASE"
        case .theaterMasks: "ICON_THEATER_MASKS"
        case .powerplug: "ICON_POWERPLUG"
        case .spigot: "ICON_SPIGOT"
        case .partyPopper: "ICON_PARTY_POPPER"
        case .ballon: "ICON_BALLON"
        case .popcorn: "ICON_POPCORN"
        case .bed: "ICON_BED"
        case .toilet: "ICON_TOILET"
        case .lock: "ICON_LOCK"
        case .key: "ICON_KEY"
        case .map: "ICON_MAP"
        case .headphones: "ICON_HEADPHONES"
        case .evCharger: "ICON_EV_CHARGER"
        case .syringe: "ICON_SYRINGE"
        case .pill: "ICON_PILL"
        case .flask: "ICON_FLASK"
        case .teddybear: "ICON_TEDDYBEAR"
        case .tree: "ICON_TREE"
        case .hanger: "ICON_HANGER"
        case .tshirt: "ICON_TSHIRT"
        case .shoe: "ICON_SHOE"
        case .film: "ICON_FILM"
        case .movieClapper: "ICON_MOVIE_CLAPPER"
        case .eyeglasses: "ICON_EYEGLASSES"
        case .clock: "ICON_CLOCK"
        case .alarm: "ICON_ALARM"
        case .gameController: "ICON_GAME_CONTROLLER"
        case .paintPalette: "ICON_PAINT_PALETTE"
        case .cupAndSaucer: "ICON_CUP_AND_SAUCER"
        case .mug: "ICON_MUG"
        case .takeout: "ICON_TAKEOUT"
        case .carrot: "ICON_CARROT"
        case .forkAndKnife: "ICON_FORK_AND_KNIFE"
        case .globeDesk: "ICON_GLOBEDESK"
        case .gift: "ICON_GIFT"
        case .battery100percent: "ICON_BATTERY_100PERCENT"
        case .iphone: "ICON_IPHONE"
        case .macbook: "ICON_MACBOOK"
        case .appleLogo: "ICON_APPLE_LOGO"
        case .applewatch: "ICON_APPLEWATCH"
        case .appleTV: "ICON_APPLETV"
        case .remote: "ICON_REMOTE"
        case .airplaneDeparture: "ICON_AIRPLANE_DEPARTURE"
        case .airplaneArrival: "ICON_AIRPLANE_ARRIVAL"
        case .airplane: "ICON_AIRPLANE"
        case .person: "ICON_PERSON"
        case .people: "ICON_PEOPLE"
        case .eyes: "ICON_EYES"
        case .mouth: "ICON_MOUTH"
        case .brain: "ICON_BRAIN"
        case .globe: "ICON_GLOBE"
        case .pawprint: "ICON_PAWPRINT"
        case .flower: "ICON_FLOWER"
        case .atom: "ICON_ATOM"
        case .heart: "ICON_HEART"
        case .stethoscope: "ICON_STETHOSCOPE"
        case .cross: "ICON_CROSS"
        case .squareRoot: "ICON_SQUARE_ROOT"
        case .function: "ICON_FUNCTION"
            
        default: "ICON_STRING"
        }
    }
}
